### ISSUE TITLE
Setting Up the Local Development Environment

### ISSUE THREAD

**Issue by Oleksandr6676** [Oleksandr6676/Bank-infra#2]
#### Objective
Set up a local development environment to work on the project. This involves cloning the repository, installing dependencies, setting up a MySQL database, and running the API to verify everything is functioning correctly.

#### Steps

1. **Clone the Repository**
   - Clone the project repository to your local machine.
   - **Command:**
     ```bash
     git clone <repository-url>
     ```

2. **Install Project Dependencies**
   - Use `poetry` to install the necessary dependencies for the project.
   - **Command:**
     ```bash
     poetry install
     ```

3. **Install and Set Up Local MySQL Database**
   - Install MySQL on your local machine if it is not already installed.
   - Create a new MySQL database for the project.
     2. Log into MySQL:
        ```bash
        mysql -u root -p
        ```
     3. Create a new database:
        ```sql
        CREATE DATABASE <your_database_name>;
        ```
     4. Update the project configuration with the database name, username, and password.

4. **Run the API and Verify the Setup**
   - Start the API by running the `main.py` file.
   - **Command:**
     ```bash
     poetry run python main.py
     ```
   - Use Postman or any other API testing tool to manually call the API endpoints and verify that the configuration is working as expected.
   - Access the Swagger documentation at `http://127.0.0.1:5000/apidocs` to view the available endpoints.

**Comment by glebmagamedov** [comment]
all steps completed successfully
